name: CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          miniforge-version: latest
          # use-mamba: true
          channels: conda-forge

      - name: Create Conda environment
        shell: bash -l {0}
        run: |
          conda install -c conda-forge openmc>=0.14.0

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install .[tests]

      - name: Run tests
        shell: bash -l {0}
        run: |
          python -m pytest test/ --cov=src/ --cov-report=xml

      - name: Run tests and collect coverage
        run: pytest --cov=openmc_fusion_benchmakrs
      - name: Upload coverage to Coveralls
        run: coveralls

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}