name: CI
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          miniforge-version: latest
          # use-mamba: true
          channels: conda-forge

      - name: Create Conda environment
        shell: bash -l {0}
        run: |
          conda install -c conda-forge openmc>=0.14.0

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install .[tests]

      - name: Run tests
        shell: bash -l {0}
        run: |
          python -m pytest test/ --cov=src/ --cov-report=xml

      - name: Test and Coverage
        run: npm run test:cov  # or npm run coverage

      # Add this
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main