name: Deploy Docs
on:
  push:
    branches:
      - docs-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean old builds
        run: rm -rf docs/_build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Change to your required version

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          miniforge-version: latest
          # use-mamba: true
          channels: conda-forge

      - name: Create Conda environment
        shell: bash -l {0}
        run: |
          conda install -c conda-forge openmc>=0.14.0
  
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install .[docs]

      - name: Build documentation with sphinx-multiversion
        shell: bash -l {0}
        run: |
          sphinx-build docs docs/_build/html
          touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          enable_jekyll: false